### ISSUE TITLE
Fix random control in README script

### ISSUE THREAD

**Issue by stephane-caron** [dojo-sim/dojopy#2]
The [Quickstart](https://github.com/dojo-sim/dojopy#quickstart) README example references an undefined ``nu`` (also a missing import of ``Base``). From test code that one is probably:

```python
# random control
from julia import Base
nu = dojo.input_dimension(env.mechanism)
u1 = Base.rand(nu)
```

**Comment by thowell** [comment]
Fixed, thanks!
